### ISSUE TITLE
Isvalid and error message issue

### ISSUE THREAD

**Issue by naveenb13** [parsajiravand/react-form-wizard#5]
Isvalid and error message given on <FormWizard.TabContent> container is not working properly. 
Validation for my input field is not working
Can anyone check this ?

**Comment by parsajiravand** [comment]
@naveenb13  
thanks for your report i will check this as soon as possible.
did you check this sample : https://react-form-wizard-component-document.netlify.app/docs/demos/validate-tab
**you must be return boolean function in IsValid prop**

**Comment by naveenb13** [comment]
@parsajiravand Yes I took the sample code only. But it is not working.
But it worked when I made a change in the sample code as validationError={errorMessages()} by making it as a function, but the alert message came at all steps. So that was making a issue.

Now I have resolved my issue by keeping custom footer button and custom functions using ref for input validations. 

But I think isvalid and errorMessage is not proper.

**Comment by parsajiravand** [comment]
@naveenb13 
thanks ,you should use validationError={errorMessages} without pranteces then its work correclty.
I will work on setup antoher ways for validation thanks.

**Comment by Naveen-ecrubit** [comment]
@parsajiravand I tried without parentheses, the function of errorMessages didnt even called. The alert inside the errorMessages didnt show up without parentheses.

**Comment by naveenb13** [comment]
@parsajiravand I tried without parentheses like the sample code, but the function of errorMessages didnt even work. So that was the issue I was facing...

Anyways thanks for your reply👍
